spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/academia
    username: root
    password: groove07
#spring.datasource.url=jdbc:mysql://localhost:3306/academia
#username:root
#password:groove07
jpa: show-sql:true
hibernate: ddl-auto:update
properties: hibernate.format.sql:true



