
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/academia?useTimeZone=true&serverTimeZone=UTC&useLegacyDate
    username: root
    password: groove07
  jpa:
    show-sql:true
  hibernate:
    ddl-auto:create
  properties:
    hibernate.format_sql:true




